### ISSUE TITLE
PWA is not implement in the demo yet？ lighthouse can't detect PWA, but still not instable?

### ISSUE THREAD

**Issue by mobilelifeful** [hbstack/pwa#58]
Thank you.

**Comment by razonyang** [comment]
Thanks for letting me know that, didn't notice that.

It's strange that the [the web manifest](https://github.com/hugomods/pwa/pull/37) is missing, I guess the output format name became case-sensitive, should be fixed since `github.com/hugomods/pwa`'s `v0.3.1`.

For fixing this on your site (if any).

```sh
hugo mod get github.com/hugomods/pwa@v0.3.1
```

![image](https://github.com/hbstack/pwa/assets/17720932/80ea2f38-bff7-411c-b0be-d7c1713a5eac)
